// Lista de bairros de Piracicaba
export const bairrosPiracicaba = [
  'Água Branca',
  'Água Santa',
  'Água Seca',
  'Alemães',
  'Alphaville Piracicaba',
  'Alto',
  'Alto da Pompéia',
  'Anhumas',
  'Área Rural de Piracicaba',
  'Areião',
  'Bongue',
  'Bosque dos Lenheiros',
  'Campestre',
  'Capim Fino',
  'Castelinho',
  'CECAP',
  'Centro',
  'Centro (Ártemis)',
  'Centro (Ibitiruna)',
  'Centro (Tupi)',
  'Centro Comercial Agrícola Taquaral',
  'Chácara Esperia',
  'Chácara Nazaré',
  'Chácara São Jorge',
  'Chácaras Água Branca',
  'Chicó',
  'Cidade Alta',
  'Cidade Jardim',
  'Colinas do Piracicaba (Ártemis)',
  'Conceição',
  'Conceição II',
  'Conjunto Habitacional Água Branca',
  'Conjunto Residencial Mário Dedini',
  'Dois Córregos',
  'Estância Lago Azul (Ártemis)',
  'Garças',
  'Glebas Califórnia',
  'Gran Park Residencial',
  'Guamium',
  'Higienópolis',
  'Horto (Tupi)',
  'Irmãos Camolesi',
  'Itaperu',
  'Jaraguá',
  'Jardim Abaeté',
  'Jardim Água Viva',
  'Jardim Algodoal',
  'Jardim Alvorada',
  'Jardim Aman',
  'Jardim Astúrias I',
  'Jardim Astúrias II',
  'Jardim Astúrias III',
  'Jardim Bartira (Tupi)',
  'Jardim Belvedere',
  'Jardim Boa Esperança',
  'Jardim Borghesi',
  'Jardim Brasília',
  'Jardim Califórnia',
  'Jardim Camargo',
  'Jardim Castor',
  'Jardim Caxambu',
  'Jardim Conceição',
  'Jardim Costa Rica',
  'Jardim Diamante',
  'Jardim Dona Luisa',
  'Jardim dos Antúrios',
  'Jardim dos Manacás',
  'Jardim Elite',
  'Jardim Esplanada',
  'Jardim Estoril',
  'Jardim Europa',
  'Jardim Flamboyant',
  'Jardim Glória',
  'Jardim Glória II',
  'Jardim Ibirapuera',
  'Jardim Ipanema',
  'Jardim Irapuã',
  'Jardim Itaiçaba (Ártemis)',
  'Jardim Itamaracá',
  'Jardim Itamaraty',
  'Jardim Itapuã',
  'Jardim Maria',
  'Jardim Maria Claudia',
  'Jardim Maria Helena',
  'Jardim Matilde II',
  'Jardim Modelo',
  'Jardim Monumento',
  'Jardim Noiva da Colina',
  'Jardim Nova Iguaçu',
  'Jardim Nova República',
  'Jardim Nova Suíça',
  'Jardim Oriente',
  'Jardim Pacaembu',
  'Jardim Parque Jupiá',
  'Jardim Paulista',
  'Jardim Petrópolis',
  'Jardim Planalto',
  'Jardim Primavera',
  'Jardim Residencial Cambuy',
  'Jardim Residencial Itabera',
  'Jardim Residencial Javary I',
  'Jardim Residencial Javary II',
  'Jardim Residencial Javary III',
  'Jardim Santa Ignês I',
  'Jardim Santa Ignês II',
  'Jardim Santa Isabel',
  'Jardim Santa Silvia',
  'Jardim São Francisco',
  'Jardim São Jorge',
  'Jardim São José',
  'Jardim São Luiz',
  'Jardim São Paulo',
  'Jardim Sol Nascente',
  'Jardim Sol Nascente II',
  'Jardim Taiguara',
  'Jardim Tarumã',
  'Jardim Tatuapé',
  'Jardim Três Marias',
  'Jupiá',
  'Loteamento Chácaras Nazareth II',
  'Loteamento Distrito Industrial Uninorte',
  'Loteamento Humberto Venturini',
  'Loteamento Ipanema',
  'Loteamento Irmãos Inforçato',
  'Loteamento Jardim Colina Verde',
  'Loteamento Jardim Monte Castelo',
  'Loteamento Jardim Santa Maria',
  'Loteamento Kobayat Líbano',
  'Loteamento Residencial e Comercial Villa D\'Aquila',
  'Loteamento Residencial Gaivotas',
  'Loteamento Residencial Reserva do Engenho',
  'Loteamento Residencial Santo Antônio II',
  'Loteamento Santa Rosa',
  'Loteamento São Francisco',
  'Loteamento Vem Viver Piracicaba I',
  'Mário Dedini',
  'Matão',
  'Monte Alegre',
  'Monte Líbano',
  'Morato',
  'Morumbi',
  'Nhô Quim',
  'Nossa Senhora de Fátima',
  'Nova América',
  'Nova Piracicaba',
  'Nova Pompéia',
  'Nova Suíça',
  'Novo Horizonte',
  'Ondas',
  'Parque Água Branca',
  'Parque Bela Vista',
  'Parque Chapadão',
  'Parque Conceição',
  'Parque Conceição II',
  'Parque dos Sabiás',
  'Parque Nossa Senhora das Graças',
  'Parque Orlanda I',
  'Parque Orlanda II',
  'Parque Orlanda III',
  'Parque Peória (Tupi)',
  'Parque Primeiro de Maio',
  'Parque Residencial Monte Rey',
  'Parque Residencial Monte Rey II',
  'Parque Residencial Monte Rey III',
  'Parque Residencial Piracicaba',
  'Parque Residencial Piracicaba Balbo',
  'Parque Santa Cecília',
  'Parque São Jorge',
  'Parque São Matheus',
  'Parque Taquaral',
  'Pau D\'Alhinho',
  'Pau Queimado',
  'Pauliceia',
  'Paulista',
  'Perdizes',
  'Piracicamirim',
  'Pompéia',
  'Prezoto',
  'Residencial Alto da Boa Vista',
  'Residencial Altos do Piracicaba',
  'Residencial Andorinhas',
  'Residencial Bela Vista',
  'Residencial Bertolucci',
  'Residencial Itaporanga',
  'Residencial Mont Carlo',
  'Residencial Nova Água Branca II',
  'Residencial Paineiras',
  'Residencial Portal da Água Branca',
  'Residencial Santo Antônio',
  'Residencial Serra Verde',
  'Residencial Terras de Ártemis (Ártemis)',
  'Santa Olímpia',
  'Santa Rita',
  'Santa Rosa',
  'Santa Rosa Ipês',
  'Santa Terezinha',
  'Santana',
  'São Dimas',
  'São Jorge',
  'São Judas',
  'São Luiz',
  'Sertãozinho',
  'Tanquinho (Guamium)',
  'Taquaral',
  'Terra Nova',
  'Terras de Piracicaba',
  'Terras do Engenho',
  'Unileste',
  'Vale do Sol',
  'Verde',
  'Vila Belém',
  'Vila Bessy',
  'Vila Cristina',
  'Vila Fátima',
  'Vila Independência',
  'Vila Industrial',
  'Vila Monteiro',
  'Vila Nossa Senhora Aparecida',
  'Vila Nova',
  'Vila Pacaembu',
  'Vila Rezende',
  'Vila Sônia',
  'Vivendas Bela Vista',
]

// Função para verificar se uma cidade é Piracicaba
export const isPiracicaba = (cidade: string): boolean => {
  return cidade.toLowerCase() === 'piracicaba'
}

// Função para obter bairros de Piracicaba
export const getBairrosPiracicaba = (): string[] => {
  return bairrosPiracicaba
}

