-- =====================================================
-- Script SQL para importar leads de lojas em Piracicamirim
-- Execute este script no SQL Editor do Supabase
-- =====================================================

-- Inserir leads de lojas em Piracicamirim
INSERT INTO leads (id, nome, telefone, estado, cidade, bairro, nicho, status, data_criacao, origem, contactado, tem_site, lead_quente)
VALUES
  (gen_random_uuid()::text, '3 kids Loja Infantil', '(19) 99917-9834', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'GICERI MODA ÍNTIMA', '(19) 97154-0690', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Açougue Boi branco. Piracicaba sp', '(19) 3426-7495', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Marinho Agropecuária e Pet Shop - Loja 3', '(19) 3375-3325', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Piracicaba Led', '(19) 99450-1587', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Assaí Atacadista', '(19) 3401-2100', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Corbella Tintas - Piracicaba 4', '(19) 3374-4100', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Guaili | Moda Praia e Fitness | Shopping Piracicaba', '(19) 3375-0178', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Beauty Star Cosméticos & Perfumaria', '(19) 98338-6888', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Impacto Som', '(19) 3411-8203', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Floricultura Mary Clar', '(19) 99976-4459', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Gran sabor', '(19) 99266-5962', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Supermercado Beira Rio', '(19) 3447-4710', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'KMF Shopping das Baterias', '(19) 3411-1352', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Paneteria Sol Nascente', '(19) 98373-0180', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Cacau Show - Chocolates', '(19) 3428-1068', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'VL Aquarismo', '(19) 98147-9353', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Alternativa calçados', '(19) 3426-3213', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Loja Obramax Piracicaba', '(19) 3003-3400', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Loja do Mecânico Piracicaba', '(19) 3052-8181', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Pira Pisos - Pisos e Acabamentos', '(19) 3426-3820', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Varejão Dois Irmãos', '(19) 3374-5040', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Zastras Piracicaba', '(19) 99832-3909', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Piracicaba Importados', '(19) 98706-3018', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Mimo''s Armarinho', '(19) 99652-2774', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'DiÂngeli', '(19) 3426-7684', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Lm Closet Piracicaba', '(19) 99624-4905', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'RPM Store Plus Size', '(19) 98387-6910', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Agropecuária do Mané Loja Dois Corregos', '(19) 3426-3485', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'JR Pankadão', '(19) 98171-2982', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Posto GT Piracicamirim', '(19) 2532-0207', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'ADÃO SOM', '(19) 3411-1616', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Tutti Frutti', '(19) 3426-7911', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Depósito 23 - loja 2', '(19) 3434-9003', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Ótica Mercadão dos Óculos Piracicamirim - Piracicaba - SP', '(19) 99946-9449', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Maskavo Churreria', '(19) 99629-0071', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Encante Kids', '(19) 98830-5048', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'OXXO - Tapira', '0800 747 6996', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Ariane Modas', '(19) 3426-6461', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Loja Pro Gamers', '(19) 99797-7795', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Depósito Santa Rita de Piracicaba Materiais p/ Construção', '(19) 3426-0981', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Ka Moto', '(19) 3426-7247', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Suporte Smart Piracicaba - Piracicamirim', '(19) 99737-8054', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Delta Supermercados Dois Córregos - Piracicaba', '(19) 3403-5591', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'O Boticário', '(19) 97422-2725', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Fishing Express', '(19) 98172-9728', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Pássaro e Cia Pet Shop/Banho e Tosa', '(19) 99801-9968', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Laços de Fita - Piracicaba l Vila Rezende', '(19) 3413-3096', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, '21k Calçados', '(19) 3426-1137', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Paulistinha Cosméticos', '(19) 3927-2827', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Água Viva Piscina - Loja Piracicaba', '(19) 3377-9009', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'E - Veste', '(19) 3377-2236', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'BW Papelaria', '(19) 3411-4827', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Niquito Sports', '(19) 2533-1510', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Balão Mágico Moda Infantil e juvenil', '(19) 99816-4120', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Gygabon Piracicaba - Piracicamirim', '(19) 99978-7609', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Point Cell', '(19) 97406-0276', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Sousa Moto & Cia', '(19) 3426-5886', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Betta Suplementos', '(19) 3374-4896', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'MaqClima Refrigeração', '(19) 99470-6010', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Office Papelaria', '(19) 3375-6924', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Utilitá Variedades Loja 2', '(19) 3411-4188', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'CASA DAS CADEIRAS PIRACICABA', '(19) 98964-9288', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Daaz Rolamentos Ferramentas e Parafusos', '(19) 3927-6353', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Smoke Room Lounge E Tabacaria', '(19) 99964-9231', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Enxovais Cravo e Canela', '(19) 3411-1794', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Juguel Materiais de Construção', '(19) 3374-7330', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Conveniencia Petromania', '(19) 3375-5554', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Pinta Mundi Tintas Piracicaba', '(19) 98842-2233', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Magnificat Joias', '(19) 98100-9667', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Padaria Amizade 7', '(19) 97165-1337', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Maia eletrônicos e acessórios', '(19) 3927-1158', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Vilaflex Colchões', '(19) 3371-4418', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Gira Mundo Calçados', '(19) 99685-6262', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Casa dos Pães - Padaria 24 horas', '(19) 3374-5136', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Pedrinho Som, Sistema de Multimídia Alarmes e Travas Elétricas Piracicaba', '(19) 99728-5897', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Ana Clothing Store', '(19) 99206-6439', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Depósito de Bebidas Eskinão', '(19) 98460-1275', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Simple Lines', '(19) 98346-6267', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Lingerie em Piracicaba - Sedução Moda Íntima', '(19) 3432-1637', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Impacto Tecidos', '(11) 91108-6051', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'JR Multimarcas', '(19) 3302-5255', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Independencia Veiculos loja 3', '(19) 3426-9050', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Trok Pneus II - Revenda Michelin', '(19) 3413-7111', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Lajes Vitória', '(19) 98329-3272', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Comercial Artmaq', '(19) 3426-3998', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'HELTONCAR RECUPERADORA ESPECIALIZADA', '(19) 97149-7504', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Geração do Som Piracicaba', '(19) 99189-7322', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Shopping Piracicaba', '(19) 3372-9553', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Manipulação Drogal', '(19) 3433-6490', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Território Pet - Agropecuária e PetShop', '(19) 98258-0813', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Puket', '(19) 3377-6199', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Elymarry Cosméticos & Cia', '(19) 3426-6319', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Espaço Malta Piracicaba', '(19) 99858-5957', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'MKL produto de limpeza', '(19) 99352-9462', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Mugs Germânia', '(19) 99563-1341', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Hausz Piracicaba', '(19) 99998-0195', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Cervejaria Dama Bier', '(19) 3401-1766', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Paulista Motos', '(19) 3426-8781', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Musclefit Academia - Piracicamirim', '(19) 98983-5286', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Loja Lurds Plus Size Piracicaba', '(19) 99188-0190', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Atacadão - Piracicaba Piracicamirim', '(19) 3372-6169', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Bazar Modelo Tecidos & Armarinhos', '(19) 3422-4241', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Patotinha Store Piracicaba', '(19) 3432-1606', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'CENTRAL DE PROTEÇÃO', '(19) 2532-6070', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Cresci e Perdi - Piracicaba', '(19) 3422-8148', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Boneca de Pano Boutique', '(19) 3426-2579', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Pipack Embalagens', '(19) 3371-8257', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Laços de Fita - Piracicaba l Jd. Petrópolis', '(19) 3411-6148', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Gustinho Eletroshow | Loja de Eletrônicos | Celular Xiaomi | Perfumes Importados | Iphone | Presentes | Piracicaba', '(19) 3426-3275', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Flafer Dois Corregos', '(19) 2532-2660', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Renata Modas', '(19) 3302-7251', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Let Brinquedos - Loja 3 - Piracicamirim', '(19) 2533-0956', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Papelaria Colegial', '(19) 3411-3727', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Lojas CEM F260', '(19) 3411-5193', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'ZEM STORE', '(19) 3036-2836', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Passe Repasse Piracicaba', '(19) 3826-7388', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Pira Cópias', '(19) 3422-2243', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Chokodoce', '(19) 3371-4699', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE),
  (gen_random_uuid()::text, 'Tecnomania Games', '(19) 98225-3758', 'SP', 'Piracicaba', 'Piracicamirim', 'Loja', 'Novo', CURRENT_DATE, 'Importação em massa', FALSE, NULL, FALSE);

-- Verificar quantos leads foram inseridos
SELECT COUNT(*) as total_leads_inseridos 
FROM leads 
WHERE bairro = 'Piracicamirim' AND nicho = 'Loja';

